language: java
jdk:
- openjdk8
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
script:
- ./gradlew check
- ./gradlew test
- ./gradlew bootJar
after_success:
- bash <(curl -s https://codecov.io/bash)